version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "peacevale"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-143voxj25jmgx"
s3_prefix = "peacevale"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
