Transform: AWS::Serverless-2016-10-31

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: peacevaleweb
      WebsiteConfiguration:
        IndexDocument: index.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - S3:GetObject
            Principal: "*"
            Resource: "arn:aws:s3:::peacevaleweb/*"
  CloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - S3Bucket
      - S3BucketPolicy
    Properties:
      DistributionConfig:
        Aliases: 
          - peacevale.rpg.chalupaul.com
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt S3Bucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateManagerCertificate
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: rpg.chalupaul.com
      RecordSets:
      - Name: peacevale
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistro.DomainName
          EvaluateTargetHealth: false
        HostedZoneId: Z01554673UC7WST1TADVK
  CertificateManagerCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: peacevale.rpg.chalupaul.com
      ValidationMethod: DNS
  